Numpy

In [1]:
import numpy as np

In [2]:
a = [[11,12,13],[21,22,23],[31,32,33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [5]:
A.ndim #How many dementions

2

In [8]:
A.shape #HOw many Sides or number of eacher dimension


(3, 3)

In [9]:
A.size # number of elements the arry is giving by the attribute size
#Shows the numpy array size

9

In [10]:
A[1,2]

23

In [11]:
A[0][0]

11

In [12]:
A[0][0:2]

array([11, 12])

In [14]:
A[0:3][2]

array([31, 32, 33])

In [15]:
X = np.array([[1, 0], [0,1]])
X

array([[1, 0],
       [0, 1]])

In [17]:
Y = np.array([[2,1], [1,2]])
Y

array([[2, 1],
       [1, 2]])

In [18]:
Z = X + Y #Add
Z

array([[3, 1],
       [1, 3]])

In [19]:
Y = np.array([[2,1], [1,2]]) 
Y

array([[2, 1],
       [1, 2]])

In [20]:
Z = 2 * Y #Mutliplay
Z

array([[4, 2],
       [2, 4]])

In [21]:
Y = np.array([[2,1], [1,2]])
Y

array([[2, 1],
       [1, 2]])

In [22]:
X = np.array([[1,0], [0,1]])
X

array([[1, 0],
       [0, 1]])

In [23]:
Z = X * Y #multiply together
Z

array([[2, 0],
       [0, 2]])

In [24]:
A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [25]:
B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [26]:
Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [27]:
np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [28]:
C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [29]:
C.T

array([[1, 2, 3],
       [1, 2, 3]])

array([[1, 2, 3],
       [1, 2, 3]])

Questions

In [32]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
A.size

12

In [35]:
A[0][0:2]

array([1, 2])

In [38]:
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])



C = np.dot(A, B)
C

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])